language: python
python:
- 3.7
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: Tvi8TY+4CqYFGa+gB6/2kDR9xTMshLa+1TU6kJxrugPBo4ScGweucQ1InnudaERQceoIBEChgqgoEFYSWPf4+qd7jdd+1rmuQRjKLNT8f4aaPrkjZ0HnyMOqtPXc5QA/fbpCBXqkZAOzbLJXT/Zv0HVC3JOJdNzARRrrsE55nRJaiJjSxZT0qwfyvNEHwTHQEuN4aE9ER1zgUGsjjgXtgGPpia/3jpuA0W3uyP79WZ1zY02cpKlW3VSICpRTiL9Wm1/HJz1SEuJ493XTxpj7FNv0KEtUhcHkwZc3MSbi8GwhDl4neygcJmE+cZZyH3U7v7Ep8ScHXHtukfQiasFXVwlgSB4HRZRo2Up5Zt+qteQKxD2kHfSRNFskuuU53eA7Krwj3iIc85omd7KgKw53rX3RGUvRdfS36hkRk+Ta+n3wTPAoL9OCHCOvv+4LakxIwW9XJ/V6v0iOdCRas9DNsiPCip2n30DolHHjjZS+/Q7r+DRLGcFAN5sYzTy4PDgBSvUuP+ilySN2MsnKg/IR005al9z3AhCI3xHj6F1XBUbt73dthBS+XiJlJTARfnZjTkwHwYqK39LV+6nmUqVgPRRKr5KdH+5stev6FYjkuXak2RuC8FUsjgyup0N2bwEG2MPNuiDUq/Y0op2xnikllfb19j/grrUmdC1CPase4QQ=
  on:
    tags: true
    repo: SpiralOutDotEu/cookiepy
    python: 3.7
