language: python
python:
- 3.7
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: SpiralOutDotEu
  server: https://test.pypi.org/legacy/
  password:
    secure: ppmDBjINg2iZBZNxKNZidTMTFYqteRvAvioRAM2ntCUfpMzL+R9zIqATaKUAYVku3oQJjr790Nids2Ub2lFtgQEAD4zlngr4aR3Izj35O+Jwum98/RyIeIf4/s0bB5Da6jLQQH7ENt51lnzYCvEg0hxX3aLUO6ErCHxivDWpBmBwEvcBmSu+9+oFB6WfTckqFtR5uFF4oMG5KOt3g037rD4Bn/ejXuqz/peHAY+NwcbrxtKI82MD6Xqd3PqYFWBfYrJXZiVSU7jeptH87WvubeiSMfYXG55Vwu4SSBufUQGMUbS0kpeeFd4l78m5o1LUoSu4JqIR/QIRbddkc3PHiluEgaKFsQr4bhuXmhRL0Vkrm7XWq5tv08J5i1BHmyhVej2fx8FCmvxY4t42/EeynRrd0iU3qlUB6CYN4qLnarv2H6mVIIwiKD4SFJTHdri6ivxwpVddpxAiM38FZIShX5SnSy8GLAGwjTDyBZZOU1qxf9c1eLPru4ko20oHzuSaeAKKjpG+lonhpw+A9g4oDSQvwl2LC23bpFliu1P+C5d4ZVGl5Yo2ybWFV8IL1MF8KBfZH5qzpSjSUawcu0O+dPdjzA8Tg7vg6Kd55L02BbhuCBrA9W96+Pwke5yx+vKurPSIsuI4Q3iafdgcJQB0MK+4E80WQcvJiYI8XGTbguI=
  on:
    tags: true
    repo: SpiralOutDotEu/cookiepy
    python: 3.7
