language: python
python:
- 3.7
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: SpiralOutDoEu
  server: https://test.pypi.org/legacy/
  password:
    secure: sPjUZJG3MCuWQUG6iVQP/jZSm4LBOt7Mi+6nbsuos0I9vBcydr6RKdfK/c+3XyJB88NmnEu0REMW4M4xAIDjNPE0x2NERfATve2bacaNzTd67awPrF3PKiCCsLQllhsfD8AgEMC8k19SW+RaVr2Yq+CCSjvVPTElKDv2kPCHtkyZr54C7WGKZxAJ6YU8qsViOT2Ap8zouFyPGCmwGTF55nozecMfKtzE87W2njH6MKvWlVm41tZgf1mbN2CGWKAmhu0Zox/K7xPqWDM87Z41bbtkOQzudUEB8mXQg6qQf/RQpRildl7Ls9TJjNSqDV+Nh24OxTT8XHliIAF58lbUJklfDE+xzNZcyt2O2aQ07oX0UcNjqGxK2auvpKNM02RryphB8LonUmHSY5BYXyDGlsnB32etcJ4RHwHn8OXA129daAk9Un9UThO9hgSIit4gsCuzUZFHIKvlHlm9I2lsCuMTDFcE/2mCQSgWCdVqtiGQx3lPHFrWlXLWwnwp2gXwLpkW8EHnpuuX06ZdpZjIvYdXxnJBGVMCN69HFIX7uZDfAwdJ3yv9fclkAfHN24dtJrStM03UfrxNQeoIQOax0/ZLKboLJokylinA/eHJtSIUqB1YPWt3w05V41RrDvFz5E23OGOF0IyaVqfJAjAiIBJj9rjC1+PRnNtn4vTORNw=
  on:
    tags: true
    repo: SpiralOutDotEu/cookiepy
    python: 3.7
