language: python
python:
- 3.7
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: SpiralOutDoEu
  server: https://test.pypi.org/legacy/
  password:
    secure: yfB+EEoaH5GSbgkLNhskS+vNuyzKQtILedVN4jl/y/QgOKX0Ys2odhRPoba/SxU0aMQP9EzTxwBAelLXNSy0eMDLJf8lNfKO/Q8l8+H1qQ99ywZXBeTCcKjcDPH5GlzRxTDWK1oymaXNecQuHtYHsd7raZAS0E1ZkEmpfh/XwTLJHPusN2XcLsII77inC8eIpdS+L+oqc/jq6NFK6PUWKlSwk4cw4IsZSJIvvkOw+w+eMt7N/3yOOWqfbY5lKEJyw/9DCDogm7vIu+lq+ritFtb3VP3vF1VQMpmBR7cT+40+fTNB0/FDrYM/XfNcDTPSUj6/gXMeeuDHxHIkBA4ianVGksEXAlGlQ53WfKN9YuPsnWH4mfllP4ni1Fyp1F71LwDzJpKvVKWLEO//5uVXMNNQP0EpD3s2QGkekEG5igVunoDW0LI5fPrMXu3lrexMG8TBYaRda3ALidCqrZPsvXMEr9ilmqb34Gd4iWdtzqch2Y++5qmxQbQwkvpILr0adgG4ddxi13pxgQgqQ/g2TQxQLxay4WNpdXR8Cx8FbBPujrD1ChqN0ZZ7U4qaNM9kdiWKEKXnXzBJQNlCJ5CMD3c78J9sKjroof31NLAY+cTz6LesIf8CT732HMA8mFfK6KTy5Z1TJ92cWw2dhgwpV1X80rgdhlxiJtmNdRxDF/o=
  on:
    tags: true
    repo: SpiralOutDotEu/cookiepy
    python: 3.7
